---
name: Add issues to project board

on:
  issues:
    types:
      - opened
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - opened

jobs:
  add-issue-to-project:
    permissions:
      issues: read
      pull-requests: read
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/add-to-project@dca9a13d483fe335f0b9edbd08494e6e4cd3b498 # v0
        with:
          # yamllint disable-line rule:line-length
          project-token: ${{ secrets.PROJECT_PAT }} # zizmor: ignore[secrets-outside-env]
