---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@7efda76137fa81805c6394236029a9cc6db0ab77 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
