---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@51b992959f67661c3433840aec883cc9ddbe2945 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
